[theme]
base = "dark"
primaryColor = "#00B4B3"
# primaryColor = "#4F46E5"
# backgroundColor = "#FFFFFF"
# secondaryBackgroundColor = "#F3F4F6"
# textColor = "#1F2937"
font = "sans serif"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
